"""Cross-process shared pricing pool for RCSPP column generation.

Architecture:
  - SharedPricingPool: holds two SharedMemory regions and a Lock.
      Region A (header):  [count: u64][n_constraints: u32][max_cols: u32][max_rows: u32]
      Region B (valid):   uint8[max_cols]
      Region C (matrix):  float64[max_cols, max_rows+1]
                          column i: [col_cost | coef_row_0 ... coef_row_{max_rows-1}]

    `price(duals)` is lock-free: reads count + valid flags + matrix with no lock.
    `add(solution)` acquires the write lock.
    `invalidate(indices)` marks deleted slots invalid (write-locked).

  - PricingPool: thin wrapper that keeps a C++ FilteredSolutionPool and a
    SharedPricingPool in sync. All C++ pool operations (remove, activity,
    filtering) go through the FilteredSolutionPool; cross-process pricing goes
    through the SharedPricingPool.
"""

from __future__ import annotations

import struct
from multiprocessing import Lock
from multiprocessing.shared_memory import SharedMemory
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from rcspp._core.graph import Solution

# ── Header layout (32 bytes) ──────────────────────────────────────────────────
_HEADER_FMT = "=QIII"  # count(u64) n_constraints(u32) max_cols(u32) max_rows(u32)
_HEADER_SIZE = struct.calcsize(_HEADER_FMT)  # 20 bytes → padded to 32 for alignment
_HEADER_BYTES = 32


class SharedPricingPool:
    """Cross-process shared pricing pool backed by SharedMemory.

    Stores LP column data (cost + row coefficients) in a dense matrix so that
    ``price(duals)`` is a single lock-free BLAS matrix-vector multiply on shared
    memory — no copy, no GIL contention.

    Args:
        n_constraints: Maximum constraint index that will ever appear in a column's
            rows.  Over-allocate generously (e.g. 1000) so new cuts added later
            don't require reallocation.
        max_cols: Maximum number of columns the pool will ever hold.
        name: Optional name for the shared memory segment.  Autogenerated if None.
    """

    def __init__(
        self,
        n_constraints: int,
        max_cols: int = 50_000,
        name: str | None = None,
        lock: object | None = None,
    ) -> None:
        self._n_constraints = n_constraints
        self._max_cols = max_cols
        # Accept an external lock (e.g. Manager().Lock() for spawn-safe use).
        self._lock = lock if lock is not None else Lock()

        # Shared memory layout:
        #   [header: _HEADER_BYTES]
        #   [valid: max_cols * 1 byte]
        #   [matrix: max_cols * (n_constraints+1) * 8 bytes]
        valid_bytes = max_cols
        matrix_bytes = max_cols * (n_constraints + 1) * 8
        total = _HEADER_BYTES + valid_bytes + matrix_bytes

        self._shm = SharedMemory(name=name, create=True, size=total)
        # Zero-initialise (ensures matrix is all-zeros for fresh columns).
        self._shm.buf[:total] = b"\x00" * total

        # Write initial header.
        struct.pack_into(_HEADER_FMT, self._shm.buf, 0, 0, n_constraints, max_cols, 0)

        self._valid_offset = _HEADER_BYTES
        self._matrix_offset = _HEADER_BYTES + valid_bytes

        # Numpy views into the shared memory buffer (zero-copy).
        self._valid = np.ndarray(
            (max_cols,),
            dtype=np.uint8,
            buffer=self._shm.buf,
            offset=self._valid_offset,
        )
        self._matrix = np.ndarray(
            (max_cols, n_constraints + 1),
            dtype=np.float64,
            buffer=self._shm.buf,
            offset=self._matrix_offset,
        )

    # ── Attach to an existing pool ────────────────────────────────────────────

    @classmethod
    def attach(cls, handle: dict) -> "SharedPricingPool":
        """Attach to an existing SharedPricingPool from another process.

        Args:
            handle: dict returned by :meth:`handle`.

        Returns:
            A new SharedPricingPool attached to the same shared memory.
        """
        obj = object.__new__(cls)
        obj._n_constraints = handle["n_constraints"]
        obj._max_cols = handle["max_cols"]
        obj._lock = handle["lock"]

        obj._shm = SharedMemory(name=handle["shm_name"], create=False)
        obj._valid_offset = _HEADER_BYTES
        obj._matrix_offset = _HEADER_BYTES + obj._max_cols

        obj._valid = np.ndarray(
            (obj._max_cols,),
            dtype=np.uint8,
            buffer=obj._shm.buf,
            offset=obj._valid_offset,
        )
        obj._matrix = np.ndarray(
            (obj._max_cols, obj._n_constraints + 1),
            dtype=np.float64,
            buffer=obj._shm.buf,
            offset=obj._matrix_offset,
        )
        return obj

    def handle(self) -> dict:
        """Return a picklable handle for passing to worker processes.

        Returns:
            dict with ``shm_name``, ``lock``, ``n_constraints``, ``max_cols``.
        """
        return {
            "shm_name": self._shm.name,
            "lock": self._lock,
            "n_constraints": self._n_constraints,
            "max_cols": self._max_cols,
        }

    # ── Write operations ──────────────────────────────────────────────────────

    def add(self, solution: "Solution") -> int:
        """Add a solution's LP column to the shared pool.

        Args:
            solution: Solution object with a populated ``column`` attribute.

        Returns:
            The shared index of the added column (for use with :meth:`invalidate`).

        Raises:
            RuntimeError: If the pool is full (count >= max_cols).
        """
        col = solution.column
        row_vec = np.zeros(self._n_constraints, dtype=np.float64)
        for row in col.rows:
            if row.index < self._n_constraints:
                row_vec[row.index] = float(row.coefficient)

        with self._lock:
            (count,) = struct.unpack_from("=Q", self._shm.buf, 0)
            if count >= self._max_cols:
                raise RuntimeError(f"SharedPricingPool is full ({count}/{self._max_cols})")
            idx = int(count)
            self._matrix[idx, 0] = col.cost
            self._matrix[idx, 1:] = row_vec
            self._valid[idx] = 1
            struct.pack_into("=Q", self._shm.buf, 0, count + 1)
        return idx

    def invalidate(self, shared_indices: list[int]) -> None:
        """Mark columns as deleted so they are skipped during pricing.

        Args:
            shared_indices: List of shared indices to invalidate.
        """
        with self._lock:
            for i in shared_indices:
                self._valid[i] = 0

    # ── Pricing ───────────────────────────────────────────────────────────────

    def price(
        self,
        duals: np.ndarray,
        threshold: float = 0.0,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Compute reduced costs for all valid columns.  Lock-free.

        ``rc[i] = col_cost[i] - matrix[i, 1:n+1] @ duals``

        where n = min(len(duals), n_constraints).

        Dynamic rows: if new cuts have been added since the pool was created,
        pass a longer ``duals`` vector.  Old columns have coefficient 0 for
        new rows (zero-filled at allocation), so they are handled correctly.

        Args:
            duals: 1-D float64 array of LP dual values, indexed by constraint.
            threshold: Return only columns with reduced cost < threshold.

        Returns:
            Tuple (indices, reduced_costs) — both 1-D arrays with the same length.
            ``indices`` are positions in the shared matrix.
        """
        # Single u64 read — safe without lock on x86/arm64.
        (count,) = struct.unpack_from("=Q", self._shm.buf, 0)
        if count == 0:
            return np.empty(0, dtype=np.intp), np.empty(0, dtype=np.float64)

        n = int(count)
        n_duals = min(len(duals), self._n_constraints)

        valid = self._valid[:n].astype(bool)
        mat = self._matrix[:n]  # zero-copy view

        rc = mat[valid, 0] - mat[valid, 1 : 1 + n_duals] @ duals[:n_duals]

        active_indices = np.where(valid)[0]
        mask = rc < threshold
        return active_indices[mask], rc[mask]

    # ── Cleanup ───────────────────────────────────────────────────────────────

    def close(self) -> None:
        """Detach from the shared memory segment (does not destroy it)."""
        self._shm.close()

    def unlink(self) -> None:
        """Destroy the shared memory segment.

        Call from the owner process only.
        """
        self._shm.close()
        self._shm.unlink()

    def __del__(self) -> None:
        try:
            self._shm.close()
        except Exception:  # noqa: BLE001
            pass

    # ── Properties ───────────────────────────────────────────────────────────

    @property
    def count(self) -> int:
        """Number of columns ever added (including invalidated ones)."""
        (count,) = struct.unpack_from("=Q", self._shm.buf, 0)
        return int(count)

    @property
    def matrix_view(self) -> np.ndarray:
        """Zero-copy numpy view of the full LP matrix (shape: [max_cols, n+1])."""
        return self._matrix

    @property
    def valid_view(self) -> np.ndarray:
        """Zero-copy numpy view of the valid flags (shape: [max_cols])."""
        return self._valid


class PricingPool:
    """Keeps a C++ FilteredSolutionPool and a SharedPricingPool in sync.

    All add/remove/activity/filtering operations delegate to the C++ pool.
    Cross-process pricing uses the shared memory pool.

    The master process creates a PricingPool; worker processes call
    ``shared_handle()`` to get a handle and ``SharedPricingPool.attach(handle)``
    to price from shared memory without any C++ dependency.

    Args:
        filtered_pool: An existing FilteredSolutionPool from the C++ bindings.
        n_constraints: Passed to SharedPricingPool — should be at least as large
            as the highest row index that will appear in any column.
        max_cols: Maximum columns the shared pool will ever hold.

    Example::

        pool = SolutionPool()
        pp = PricingPool(pool.new_filter(), n_constraints=200, max_cols=50_000)
        handle = pp.shared_handle()

        # worker:
        shared = SharedPricingPool.attach(handle)
        indices, rcs = shared.price(duals)
    """

    def __init__(
        self,
        filtered_pool: object,
        n_constraints: int,
        max_cols: int = 50_000,
    ) -> None:
        self._fp = filtered_pool
        self._shared = SharedPricingPool(n_constraints=n_constraints, max_cols=max_cols)
        # Maps C++ ColumnId → shared_index for invalidation on removal.
        self._id_to_idx: dict[int, int] = {}

    def shared_handle(self) -> dict:
        """Return a picklable handle for workers to attach to the shared pool.

        Returns:
            dict passed to :meth:`SharedPricingPool.attach`.
        """
        return self._shared.handle()

    # ── Write operations (keep both pools in sync) ────────────────────────────

    def add(self, solution: "Solution") -> int:
        """Add a solution to both the C++ pool and the shared pricing pool.

        Args:
            solution: Solution to add.

        Returns:
            The C++ ColumnId assigned by the pool.
        """
        cpp_id = self._fp.add(solution)
        shared_idx = self._shared.add(solution)
        self._id_to_idx[cpp_id] = shared_idx
        return cpp_id

    def remove_stale(self, max_age: int, min_usage_rate: float = 0.0) -> list[int]:
        """Remove stale columns from both pools.

        Args:
            max_age: Columns with age > max_age are removed.
            min_usage_rate: Columns with usage_rate < this are removed (once priced).

        Returns:
            List of removed C++ ColumnIds.
        """
        removed_ids = self._fp.remove_stale(max_age, min_usage_rate)
        self._shared.invalidate(
            [self._id_to_idx.pop(i) for i in removed_ids if i in self._id_to_idx]
        )
        return removed_ids

    # ── Pricing ───────────────────────────────────────────────────────────────

    def price_shared(
        self,
        duals: np.ndarray,
        threshold: float = 0.0,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Lock-free cross-process pricing on shared memory.

        Args:
            duals: 1-D float64 array of LP dual values.
            threshold: Return only columns with reduced cost < threshold.

        Returns:
            Tuple (indices, reduced_costs).
        """
        return self._shared.price(duals, threshold)

    def __getattr__(self, name: str) -> object:
        """Delegate unknown attributes to the underlying FilteredSolutionPool."""
        return getattr(self._fp, name)

    def close(self) -> None:
        """Release the shared memory segment."""
        self._shared.unlink()
