// Copyright (c) 2025 Laboratory for Combinatorial Optimization in Real-time Environment.
// All rights reserved.

#pragma once

// Automatically generated umbrella header

#include "rcspp/algorithm/algorithm.hpp"
#include "rcspp/algorithm/algorithm_with_iterators.hpp"
#include "rcspp/algorithm/dominance_algorithm_iterators.hpp"
#include "rcspp/algorithm/solution.hpp"
#include "rcspp/general/clonable.hpp"
#include "rcspp/graph/arc.hpp"
#include "rcspp/graph/graph.hpp"
#include "rcspp/graph/node.hpp"
#include "rcspp/graph/row.hpp"
#include "rcspp/label/label.hpp"
#include "rcspp/label/label_factory.hpp"
#include "rcspp/label/label_pool.hpp"
#include "rcspp/rcspp.hpp"
#include "rcspp/resource/base/expander.hpp"
#include "rcspp/resource/base/resource.hpp"
#include "rcspp/resource/base/resource_base.hpp"
#include "rcspp/resource/base/resource_factory.hpp"
#include "rcspp/resource/composition/functions/cost/component_cost_function.hpp"
#include "rcspp/resource/composition/functions/cost/composition_cost_function.hpp"
#include "rcspp/resource/composition/functions/dominance/component_dominance_function.hpp"
#include "rcspp/resource/composition/functions/dominance/composition_dominance_function.hpp"
#include "rcspp/resource/composition/functions/expansion/composition_expansion_function.hpp"
#include "rcspp/resource/composition/functions/feasibility/composition_feasibility_function.hpp"
#include "rcspp/resource/composition/resource_composition.hpp"
#include "rcspp/resource/composition/resource_composition_factory.hpp"
#include "rcspp/resource/concrete/functions/cost/real_value_cost_function.hpp"
#include "rcspp/resource/concrete/functions/dominance/real_value_dominance_function.hpp"
#include "rcspp/resource/concrete/functions/expansion/real_addition_expansion_function.hpp"
#include "rcspp/resource/concrete/functions/expansion/time_window_expansion_function.hpp"
#include "rcspp/resource/concrete/functions/feasibility/min_max_feasibility_function.hpp"
#include "rcspp/resource/concrete/functions/feasibility/time_window_feasibility_function.hpp"
#include "rcspp/resource/concrete/real_resource.hpp"
#include "rcspp/resource/concrete/real_resource_factory.hpp"
#include "rcspp/resource/functions/cost/cost_function.hpp"
#include "rcspp/resource/functions/cost/trivial_cost_function.hpp"
#include "rcspp/resource/functions/dominance/dominance_function.hpp"
#include "rcspp/resource/functions/dominance/trivial_dominance_function.hpp"
#include "rcspp/resource/functions/expansion/expansion_function.hpp"
#include "rcspp/resource/functions/expansion/trivial_expansion_function.hpp"
#include "rcspp/resource/functions/feasibility/feasibility_function.hpp"
#include "rcspp/resource/functions/feasibility/trivial_feasibility_function.hpp"
#include "rcspp/resource/resource_graph.hpp"
#include "rcspp/resource/resource_traits.hpp"
