// Copyright (c) 2025 Laboratory for Combinatorial Optimization in Real-time Environment.
// All rights reserved.

#pragma once

// Phase 13: does the bidirectional algorithm produce the same answers as the forward one?
//
// The order here is deliberate and is the phase's whole point: correctness first, speed afterwards.
// **A policy that loses solutions looks fast.** Benchmark first and a large speedup tells you
// nothing about whether the work or the answers were pruned.
//
// What is compared, and what is not:
//
//   - **Best cost, within tolerance, never with `==`.** A forward run accumulates one chain of
//     additions; a joined path sums two independently accumulated chains, so the association order
//     differs and the totals disagree in the last bits.
//   - **Every returned path is replayed** through the model arc by arc and must be feasible at
//   every
//     node, contiguous, and run from a source to a sink. This is the check that catches a bad merge
//     producing a path neither algorithm would have generated by extension -- both would agree on
//     its cost while one returns nonsense.
//   - **Brute force**, on the small end: an enumerator that shares no code with either algorithm,
//   so
//     a dominance error common to both still shows up.
//
// What is NOT compared is the full solution *set*, which the phase plan asks for. The two
// algorithms do not have that property and cannot: a path whose forward prefix survives dominance
// at every node can still have a backward half that is dominated at the crossing node, so the join
// never emits it. Optimality is unaffected -- the dominating half yields a path at least as good --
// but the sets differ, and asserting equality would be a test that fails for a reason that is not a
// defect. `SolutionSetsAgreeOnTheOptimumNotOnEveryPath` pins the weaker property that does hold.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <limits>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>

#include "rcspp/rcspp.hpp"
#include "util/equivalence_helpers.hpp"
#include "util/random_instance.hpp"

using namespace rcspp;  // NOLINT(google-build-using-namespace)

// ============================================================================
// The equivalence sweep
// ============================================================================

/// @brief Bidirectional matches the forward search on every generated instance, bound on and off.
TEST(Equivalence, MatchesTheForwardSearchAcrossTheSweep) {
    namespace eq = equivalence_test;

    for (const auto& config : eq::sweep()) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const eq::Run reference = eq::solve_forward(config);
        const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
        const eq::Run unbounded = eq::solve_bidirectional(config, /*with_bound=*/false);

        EXPECT_EQ(reference.result.solutions.empty(), bounded.result.solutions.empty())
            << "one found solutions and the other did not: " << where;
        EXPECT_EQ(reference.result.solutions.empty(), unbounded.result.solutions.empty()) << where;

        if (!reference.result.solutions.empty()) {
            EXPECT_NEAR(bounded.best_cost(), reference.best_cost(), eq::kTolerance)
                << "bound enabled: " << where;
            EXPECT_NEAR(unbounded.best_cost(), reference.best_cost(), eq::kTolerance)
                << "bound disabled: " << where;
        }

        EXPECT_EQ(eq::any_path_problem(bounded), "") << "bound enabled: " << where;
        EXPECT_EQ(eq::any_path_problem(unbounded), "") << "bound disabled: " << where;
    }
}

/// @brief The bound never changes the answer, only how much work is done to reach it.
///
/// Asserted separately from the comparison against the forward search so that a disagreement is
/// attributable: if both bidirectional runs match each other but not the reference, the join is
/// wrong; if they disagree with each other, the half-way policy is.
TEST(Equivalence, TheHalfWayBoundDoesNotChangeTheAnswer) {
    namespace eq = equivalence_test;

    size_t instances_with_the_bound_in_force = 0;
    for (const auto& config : eq::sweep()) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
        const eq::Run unbounded = eq::solve_bidirectional(config, /*with_bound=*/false);

        EXPECT_NEAR(bounded.best_cost(), unbounded.best_cost(), eq::kTolerance) << where;
        EXPECT_FALSE(unbounded.bounded) << "half_way_point = 0 must leave the bound off: " << where;
        if (bounded.bounded) {
            ++instances_with_the_bound_in_force;
        }
    }

    // Otherwise the whole sweep would be measuring the disabled path twice and the "bound enabled"
    // half of every assertion above would be vacuous.
    EXPECT_GT(instances_with_the_bound_in_force, 0U)
        << "no instance in the sweep actually ran with the bound enabled";
}

/// @brief On cost-only instances there is no clock, so the bound refuses to engage.
///
/// Cost is the one resource that can never be the critical one -- reduced costs go negative -- and
/// the sweep deliberately contains instances with nothing else to point at.
TEST(Equivalence, ACostOnlyInstanceRunsWithTheBoundOff) {
    namespace eq = equivalence_test;
    const test_util::InstanceConfig config{.num_nodes = 10, .density = 0.4, .seed = 101};

    const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
    EXPECT_FALSE(bounded.bounded) << "an accumulating cost slot is not a clock";
    EXPECT_NEAR(bounded.best_cost(), eq::solve_forward(config).best_cost(), eq::kTolerance);
}

// ============================================================================
// The independent oracle
// ============================================================================

/// @brief Both algorithms match an enumerator that shares no code with either.
///
/// Restricted to the small, sparse end: enumeration is exponential. It is worth having anyway --
/// comparing two label-setting algorithms cannot catch a dominance rule that is wrong in the same
/// way in both.
TEST(Equivalence, BothMatchBruteForceOnSmallInstances) {
    namespace eq = equivalence_test;

    const std::vector<test_util::InstanceConfig> configs{
        {.num_nodes = 8, .density = 0.4, .seed = 21},
        {.num_nodes = 9, .density = 0.3, .with_time_window = true, .window_slack = 0.3, .seed = 22},
        {.num_nodes = 9, .density = 0.3, .with_capacity = true, .capacity_binds = true, .seed = 23},
        {.num_nodes = 10, .density = 0.25, .mixed_sign_costs = true, .seed = 24},
        {.num_nodes = 10,
         .density = 0.25,
         .with_time_window = true,
         .window_slack = 0.4,
         .with_capacity = true,
         .capacity_binds = true,
         .num_sinks = 2,
         .seed = 25},
    };

    for (const auto& config : configs) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const double expected = test_util::brute_force_optimum(config);
        EXPECT_NEAR(eq::solve_forward(config).best_cost(), expected, eq::kTolerance)
            << "the forward search disagrees with enumeration: " << where;
        EXPECT_NEAR(eq::solve_bidirectional(config, /*with_bound=*/true).best_cost(),
                    expected,
                    eq::kTolerance)
            << "bidirectional disagrees with enumeration: " << where;
    }
}

/// @brief The solution sets agree on the optimum, and bidirectional never invents a path.
///
/// The phase plan asks for full set equality. That property does not hold and cannot: a path may
/// have a forward prefix that survives dominance everywhere and a backward half that is dominated
/// at the crossing node, in which case the join never emits it. What does hold is that every path
/// bidirectional returns is a genuine path of the graph, and that the optimum is among them.
TEST(Equivalence, SolutionSetsAgreeOnTheOptimumNotOnEveryPath) {
    namespace eq = equivalence_test;
    const test_util::InstanceConfig config{.num_nodes = 12,
                                           .density = 0.5,
                                           .with_time_window = true,
                                           .window_slack = 0.4,
                                           .seed = 31};
    const std::string where = test_util::describe(config);

    const eq::Run reference = eq::solve_forward(config);
    const eq::Run candidate = eq::solve_bidirectional(config, /*with_bound=*/true);
    ASSERT_FALSE(reference.result.solutions.empty()) << where;
    ASSERT_FALSE(candidate.result.solutions.empty()) << where;

    EXPECT_NEAR(candidate.best_cost(), reference.best_cost(), eq::kTolerance) << where;
    EXPECT_EQ(eq::any_path_problem(candidate), "") << where;

    // Every optimal path bidirectional returns must be one the forward search would accept as a
    // path, which replaying already establishes; the set sizes are allowed to differ.
    const size_t optimal_paths =
        static_cast<size_t>(std::ranges::count_if(candidate.result.solutions, [&](const auto& s) {
            return std::abs(s.cost - candidate.best_cost()) < eq::kTolerance;
        }));
    EXPECT_GT(optimal_paths, 0U) << where;
}
