// Copyright (c) 2025 Laboratory for Combinatorial Optimization in Real-time Environment.
// All rights reserved.

#pragma once

// Phase 13: does the bidirectional algorithm produce the same answers as the forward one?
//
// The order here is deliberate and is the phase's whole point: correctness first, speed afterwards.
// **A policy that loses solutions looks fast.** Benchmark first and a large speedup tells you
// nothing about whether the work or the answers were pruned.
//
// What is compared, and what is not:
//
//   - **Best cost, within tolerance, never with `==`.** A forward run accumulates one chain of
//     additions; a joined path sums two independently accumulated chains, so the association order
//     differs and the totals disagree in the last bits.
//   - **Every returned path is replayed** through the model arc by arc and must be feasible at
//   every
//     node, contiguous, and run from a source to a sink. This is the check that catches a bad merge
//     producing a path neither algorithm would have generated by extension -- both would agree on
//     its cost while one returns nonsense.
//   - **Brute force**, on the small end: an enumerator that shares no code with either algorithm,
//   so
//     a dominance error common to both still shows up.
//
// What is NOT compared is the full solution *set*, which the phase plan asks for. The two
// algorithms do not have that property and cannot: a path whose forward prefix survives dominance
// at every node can still have a backward half that is dominated at the crossing node, so the join
// never emits it. Optimality is unaffected -- the dominating half yields a path at least as good --
// but the sets differ, and asserting equality would be a test that fails for a reason that is not a
// defect. `SolutionSetsAgreeOnTheOptimumNotOnEveryPath` pins the weaker property that does hold.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <limits>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>

#include "rcspp/rcspp.hpp"
#include "util/random_instance.hpp"

using namespace rcspp;  // NOLINT(google-build-using-namespace)

namespace equivalence_test {

using Composed = ResourceTypeComposition<RealResource>;
using Graph = ResourceGraph<RealResource>;

// The ng variant's pack: a container component alongside the scalar clock. Declared here so the
// replay helpers below can serve both, which is the whole reason they are templates.
using NgComposed = ResourceTypeComposition<RealResource, SizeTBitsetResource>;
using NgGraph = ResourceGraph<RealResource, SizeTBitsetResource>;

constexpr double kTolerance = 1e-9;

/// @brief A solve and the graph it ran on, kept together so the paths can be replayed afterwards.
///
/// Templated on both the graph and its composition because @c ResourceGraph keeps its
/// composition alias private, so it cannot be recovered from @p GraphType.
///
/// @tparam GraphType   The concrete @c ResourceGraph instantiation.
/// @tparam ComposedType The matching @c ResourceTypeComposition.
template <typename GraphType, typename ComposedType>
struct RunT {
        std::unique_ptr<GraphType> graph;
        SolveResult result;
        bool bounded = false;

        using Composition = ComposedType;

        [[nodiscard]] double best_cost() const {
            return result.solutions.empty() ? std::numeric_limits<double>::infinity()
                                            : result.solutions.front().cost;
        }
};

/// @brief The single-type run, which every existing test uses. Unchanged in behaviour.
using Run = RunT<Graph, Composed>;

/// @brief The two-slot run carrying an ng-path component.
using NgRun = RunT<NgGraph, NgComposed>;

/// @brief The reference: an ordinary forward search.
inline Run solve_forward(const test_util::InstanceConfig& config) {
    Run run;
    auto built = test_util::build_instance(config);
    run.graph = std::move(built.graph);
    run.result = run.graph->solve<SimpleDominanceAlgorithm>(AlgorithmBaseParams{});
    return run;
}

/// @brief The candidate.
///
/// @param config       The instance to build.
/// @param with_bound   When false the half-way point is left at 0, which leaves the policy with no
///                     explicit `H` and no finite `R` to derive one from, so it starts disabled.
///                     That is the correct-but-slow path, and running every instance both ways is
///                     what isolates a disagreement to the bound rather than to the join.
inline Run solve_bidirectional(const test_util::InstanceConfig& config, bool with_bound) {
    Run run;
    auto built = test_util::build_instance(config);
    run.graph = std::move(built.graph);

    AlgorithmParams<LabelList<Composed>> params;
    params.critical_resource_index = built.clock_index;
    params.half_way_point = with_bound ? built.clock_upper_bound / 2.0 : 0.0;

    auto algorithm =
        run.graph->create_algorithm<BidirectionalAlgoBound<RealResource>::Algo>(params);
    run.result = run.graph->solve(algorithm.get());
    run.bounded = algorithm->bounded_by_half_way();
    EXPECT_TRUE(algorithm->get_label_pool().check_ref_count_consistency())
        << "reference counts must survive two searches and a join";
    return run;
}

/// @brief The reference, on the ng model.
///
/// A twin rather than a template: it calls `build_ng_instance` by name, and keeping the two
/// visible separately keeps the critical-resource binding visible at each site. The clock is
/// still a `RealResource`, so `BidirectionalAlgoBound<RealResource>::Algo` is unchanged.
inline NgRun solve_forward_ng(const test_util::InstanceConfig& config) {
    NgRun run;
    auto built = test_util::build_ng_instance(config);
    run.graph = std::move(built.graph);
    run.result = run.graph->solve<SimpleDominanceAlgorithm>(AlgorithmBaseParams{});
    return run;
}

/// @brief The candidate, on the ng model.
///
/// @param config     The instance to build.
/// @param with_bound As in @c solve_bidirectional: false leaves the half-way point at 0, so the
///                   policy starts disabled.
inline NgRun solve_bidirectional_ng(const test_util::InstanceConfig& config, bool with_bound) {
    NgRun run;
    auto built = test_util::build_ng_instance(config);
    run.graph = std::move(built.graph);

    AlgorithmParams<LabelList<NgComposed>> params;
    params.critical_resource_index = built.clock_index;
    params.half_way_point = with_bound ? built.clock_upper_bound / 2.0 : 0.0;

    auto algorithm =
        run.graph->create_algorithm<BidirectionalAlgoBound<RealResource>::Algo>(params);
    run.result = run.graph->solve(algorithm.get());
    run.bounded = algorithm->bounded_by_half_way();
    EXPECT_TRUE(algorithm->get_label_pool().check_ref_count_consistency())
        << "reference counts must survive two searches and a join";
    return run;
}

/// @brief Replays one path through the model, returning what is wrong with it, or "".
///
/// Extends a fresh source resource arc by arc exactly as the search would, and requires every
/// intermediate node to be feasible. Mirrors what `FeasibilityPreprocessor` does with an arc's
/// extender, which is the only route to an arc's stored consumption.
template <typename ComposedType>
inline std::string path_problem(const rcspp::Graph<ComposedType>& graph, const Solution& solution) {
    if (solution.path_arc_ids.empty()) {
        return "empty path";
    }

    const auto* first = graph.get_arc(solution.path_arc_ids.front());
    if (first == nullptr) {
        return "unknown arc id";
    }
    if (!first->origin->source) {
        return "path does not start at a source";
    }

    auto current = std::make_unique<Resource<ComposedType>>(*first->origin->resource);
    const Arc<ComposedType>* previous = nullptr;

    for (size_t arc_id : solution.path_arc_ids) {
        const auto* arc = graph.get_arc(arc_id);
        if (arc == nullptr) {
            return "unknown arc id";
        }
        if (previous != nullptr && previous->destination != arc->origin) {
            return "path is not contiguous at arc " + std::to_string(arc_id);
        }
        if (arc->extender == nullptr) {
            return "arc has no extender";
        }

        auto extended = std::make_unique<Resource<ComposedType>>(*arc->destination->resource);
        arc->extender->extend(*current, extended.get());
        if (!extended->is_feasible()) {
            return "path is infeasible at node " + std::to_string(arc->destination->id);
        }
        current = std::move(extended);
        previous = arc;
    }

    if (!previous->destination->sink) {
        return "path does not end at a sink";
    }
    return "";
}

/// @brief Replays every returned path and reports the first problem found.
template <typename GraphType, typename ComposedType>
inline std::string any_path_problem(const RunT<GraphType, ComposedType>& run) {
    for (const auto& solution : run.result.solutions) {
        const std::string problem = path_problem<ComposedType>(*run.graph, solution);
        if (!problem.empty()) {
            return problem;
        }
    }
    return "";
}

/// @brief The configurations the sweep runs, one per interesting combination of knobs.
///
/// Chosen rather than sampled: each row turns on one dimension the phase plan names, so a failure
/// points at a dimension instead of at "randomness". Seeds vary per row so the rows are not
/// correlated draws of the same graph.
inline std::vector<test_util::InstanceConfig> sweep() {
    std::vector<test_util::InstanceConfig> configs;

    // Cost only, sparse and dense. The clock is the cost slot, so the bound must switch itself off.
    configs.push_back({.num_nodes = 10, .density = 0.2, .seed = 1});
    configs.push_back({.num_nodes = 12, .density = 0.9, .seed = 2});

    // Time windows, loose and tight. Tight windows are where bidirectional wins and where a wrong
    // deadline shows.
    configs.push_back({.num_nodes = 14,
                       .density = 0.4,
                       .with_time_window = true,
                       .window_slack = 2.0,
                       .seed = 3});
    configs.push_back({.num_nodes = 14,
                       .density = 0.4,
                       .with_time_window = true,
                       .window_slack = 0.05,
                       .seed = 4});
    configs.push_back({.num_nodes = 24,
                       .density = 0.6,
                       .with_time_window = true,
                       .window_slack = 0.2,
                       .seed = 5});

    // Capacity, binding and not -- the Threshold clamp on its own.
    configs.push_back({.num_nodes = 12,
                       .density = 0.5,
                       .with_capacity = true,
                       .capacity_binds = true,
                       .seed = 6});
    configs.push_back({.num_nodes = 12,
                       .density = 0.5,
                       .with_capacity = true,
                       .capacity_binds = false,
                       .seed = 7});

    // Both, so the composition fans out over three components.
    configs.push_back({.num_nodes = 16,
                       .density = 0.5,
                       .with_time_window = true,
                       .window_slack = 0.5,
                       .with_capacity = true,
                       .capacity_binds = true,
                       .seed = 8});

    // Mixed-sign costs: the completion bound and the monotonicity fallback.
    configs.push_back({.num_nodes = 14, .density = 0.5, .mixed_sign_costs = true, .seed = 9});
    configs.push_back({.num_nodes = 18,
                       .density = 0.4,
                       .with_time_window = true,
                       .window_slack = 0.5,
                       .mixed_sign_costs = true,
                       .seed = 10});

    // Two sinks with different windows: per-node backward seeding.
    configs.push_back({.num_nodes = 15,
                       .density = 0.5,
                       .with_time_window = true,
                       .window_slack = 0.5,
                       .num_sinks = 2,
                       .seed = 11});
    configs.push_back({.num_nodes = 15,
                       .density = 0.5,
                       .with_capacity = true,
                       .capacity_binds = true,
                       .mixed_sign_costs = true,
                       .num_sinks = 2,
                       .seed = 12});

    // The large end, to catch anything that only appears with many labels per node.
    configs.push_back({.num_nodes = 40,
                       .density = 0.3,
                       .with_time_window = true,
                       .window_slack = 0.3,
                       .with_capacity = true,
                       .capacity_binds = true,
                       .seed = 13});

    return configs;
}

}  // namespace equivalence_test

// ============================================================================
// The equivalence sweep
// ============================================================================

/// @brief Bidirectional matches the forward search on every generated instance, bound on and off.
TEST(Equivalence, MatchesTheForwardSearchAcrossTheSweep) {
    namespace eq = equivalence_test;

    for (const auto& config : eq::sweep()) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const eq::Run reference = eq::solve_forward(config);
        const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
        const eq::Run unbounded = eq::solve_bidirectional(config, /*with_bound=*/false);

        EXPECT_EQ(reference.result.solutions.empty(), bounded.result.solutions.empty())
            << "one found solutions and the other did not: " << where;
        EXPECT_EQ(reference.result.solutions.empty(), unbounded.result.solutions.empty()) << where;

        if (!reference.result.solutions.empty()) {
            EXPECT_NEAR(bounded.best_cost(), reference.best_cost(), eq::kTolerance)
                << "bound enabled: " << where;
            EXPECT_NEAR(unbounded.best_cost(), reference.best_cost(), eq::kTolerance)
                << "bound disabled: " << where;
        }

        EXPECT_EQ(eq::any_path_problem(bounded), "") << "bound enabled: " << where;
        EXPECT_EQ(eq::any_path_problem(unbounded), "") << "bound disabled: " << where;
    }
}

/// @brief The bound never changes the answer, only how much work is done to reach it.
///
/// Asserted separately from the comparison against the forward search so that a disagreement is
/// attributable: if both bidirectional runs match each other but not the reference, the join is
/// wrong; if they disagree with each other, the half-way policy is.
TEST(Equivalence, TheHalfWayBoundDoesNotChangeTheAnswer) {
    namespace eq = equivalence_test;

    size_t instances_with_the_bound_in_force = 0;
    for (const auto& config : eq::sweep()) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
        const eq::Run unbounded = eq::solve_bidirectional(config, /*with_bound=*/false);

        EXPECT_NEAR(bounded.best_cost(), unbounded.best_cost(), eq::kTolerance) << where;
        EXPECT_FALSE(unbounded.bounded) << "half_way_point = 0 must leave the bound off: " << where;
        if (bounded.bounded) {
            ++instances_with_the_bound_in_force;
        }
    }

    // Otherwise the whole sweep would be measuring the disabled path twice and the "bound enabled"
    // half of every assertion above would be vacuous.
    EXPECT_GT(instances_with_the_bound_in_force, 0U)
        << "no instance in the sweep actually ran with the bound enabled";
}

/// @brief On cost-only instances there is no clock, so the bound refuses to engage.
///
/// Cost is the one resource that can never be the critical one -- reduced costs go negative -- and
/// the sweep deliberately contains instances with nothing else to point at.
TEST(Equivalence, ACostOnlyInstanceRunsWithTheBoundOff) {
    namespace eq = equivalence_test;
    const test_util::InstanceConfig config{.num_nodes = 10, .density = 0.4, .seed = 101};

    const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
    EXPECT_FALSE(bounded.bounded) << "an accumulating cost slot is not a clock";
    EXPECT_NEAR(bounded.best_cost(), eq::solve_forward(config).best_cost(), eq::kTolerance);
}

// ============================================================================
// The independent oracle
// ============================================================================

/// @brief Both algorithms match an enumerator that shares no code with either.
///
/// Restricted to the small, sparse end: enumeration is exponential. It is worth having anyway --
/// comparing two label-setting algorithms cannot catch a dominance rule that is wrong in the same
/// way in both.
TEST(Equivalence, BothMatchBruteForceOnSmallInstances) {
    namespace eq = equivalence_test;

    const std::vector<test_util::InstanceConfig> configs{
        {.num_nodes = 8, .density = 0.4, .seed = 21},
        {.num_nodes = 9, .density = 0.3, .with_time_window = true, .window_slack = 0.3, .seed = 22},
        {.num_nodes = 9, .density = 0.3, .with_capacity = true, .capacity_binds = true, .seed = 23},
        {.num_nodes = 10, .density = 0.25, .mixed_sign_costs = true, .seed = 24},
        {.num_nodes = 10,
         .density = 0.25,
         .with_time_window = true,
         .window_slack = 0.4,
         .with_capacity = true,
         .capacity_binds = true,
         .num_sinks = 2,
         .seed = 25},
    };

    for (const auto& config : configs) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const double expected = test_util::brute_force_optimum(config);
        EXPECT_NEAR(eq::solve_forward(config).best_cost(), expected, eq::kTolerance)
            << "the forward search disagrees with enumeration: " << where;
        EXPECT_NEAR(eq::solve_bidirectional(config, /*with_bound=*/true).best_cost(),
                    expected,
                    eq::kTolerance)
            << "bidirectional disagrees with enumeration: " << where;
    }
}

/// @brief The solution sets agree on the optimum, and bidirectional never invents a path.
///
/// The phase plan asks for full set equality. That property does not hold and cannot: a path may
/// have a forward prefix that survives dominance everywhere and a backward half that is dominated
/// at the crossing node, in which case the join never emits it. What does hold is that every path
/// bidirectional returns is a genuine path of the graph, and that the optimum is among them.
TEST(Equivalence, SolutionSetsAgreeOnTheOptimumNotOnEveryPath) {
    namespace eq = equivalence_test;
    const test_util::InstanceConfig config{.num_nodes = 12,
                                           .density = 0.5,
                                           .with_time_window = true,
                                           .window_slack = 0.4,
                                           .seed = 31};
    const std::string where = test_util::describe(config);

    const eq::Run reference = eq::solve_forward(config);
    const eq::Run candidate = eq::solve_bidirectional(config, /*with_bound=*/true);
    ASSERT_FALSE(reference.result.solutions.empty()) << where;
    ASSERT_FALSE(candidate.result.solutions.empty()) << where;

    EXPECT_NEAR(candidate.best_cost(), reference.best_cost(), eq::kTolerance) << where;
    EXPECT_EQ(eq::any_path_problem(candidate), "") << where;

    // Every optimal path bidirectional returns must be one the forward search would accept as a
    // path, which replaying already establishes; the set sizes are allowed to differ.
    const size_t optimal_paths =
        static_cast<size_t>(std::ranges::count_if(candidate.result.solutions, [&](const auto& s) {
            return std::abs(s.cost - candidate.best_cost()) < eq::kTolerance;
        }));
    EXPECT_GT(optimal_paths, 0U) << where;
}

// ─────────────────────────────────────────────────────────────────────────────────────────────
// The ng-path component. Two tiers, with different claims -- see 09-ng-path-benchmark.md §2.5.
// ─────────────────────────────────────────────────────────────────────────────────────────────

// Tier 1. The ng component runs in both directions across the acyclic sweep.
//
// It cannot *reject* here: no path revisits a node on a DAG, and the two halves of a join are
// node-disjoint by construction. So the claim is coverage and non-interference -- extend and
// extend_back run, the merge test is dispatched, apply/make_side are covered by a real search
// rather than by a unit test, and the answer is unchanged -- not semantics. Tier 2 is where the
// semantics are checked.
TEST(Equivalence, NgPathComponentDoesNotChangeTheAnswerOnADag) {
    namespace eq = equivalence_test;

    for (auto config : eq::sweep()) {
        config.with_ng_path = true;
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const auto forward = eq::solve_forward_ng(config);
        for (bool with_bound : {false, true}) {
            const auto bidi = eq::solve_bidirectional_ng(config, with_bound);
            EXPECT_NEAR(bidi.best_cost(), forward.best_cost(), eq::kTolerance) << where;
            EXPECT_EQ(eq::any_path_problem(bidi), "") << where;
        }
        EXPECT_EQ(eq::any_path_problem(forward), "") << where;
    }
}

// The ng component must not change the answer it cannot constrain: on a DAG, the same instance
// with ng on and off must give the same optimum. This is what "non-interference" means, and it
// would catch an ng component that rejected something it should not.
TEST(Equivalence, NgPathIsInertOnADag) {
    namespace eq = equivalence_test;

    for (auto config : eq::sweep()) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        config.with_ng_path = false;
        const auto without = eq::solve_forward_ng(config);
        config.with_ng_path = true;
        const auto with = eq::solve_forward_ng(config);

        EXPECT_NEAR(with.best_cost(), without.best_cost(), eq::kTolerance)
            << "ng changed the optimum on an acyclic instance, where it cannot bind: " << where;
    }
}

// Tier 2. THE test: cyclic instances, where ng-feasibility actually forbids something.
//
// ┌─ Why this compares against an ENUMERATOR and not against the forward search ──────────────┐
// │ The forward search is **not a valid reference on a cyclic instance** -- it loses solutions │
// │ there. See DISABLED_CyclicOptimalityAtLargerSizes below for the measurements and the       │
// │ scope of the problem. `ng_cyclic_optimum` shares no code with either algorithm and is the  │
// │ honest reference. The acyclic sweep keeps comparing the two searches, where the forward    │
// │ one IS valid.                                                                              │
// └────────────────────────────────────────────────────────────────────────────────────────────┘
//
// Sized so the oracle *completes*: at these dimensions `ng_cyclic_optimum` enumerates every
// feasible walk rather than hitting its state budget, so the comparison is against the truth and
// not against a partial search. It throws rather than truncating, so growing this is loud.
//
// This is also the regression test for step 6: the join's disjointness check is what stops the
// joiner gluing two halves that both remember the same node. Break it and either the cost stops
// matching the oracle, or `path_problem` replays the result and reports "path is infeasible at
// node N".
TEST(Equivalence, NgPathBindsOnCyclicInstancesAndBidirectionalMatchesTheOracle) {
    namespace eq = equivalence_test;

    for (unsigned seed = 0; seed < 6; ++seed) {
        test_util::InstanceConfig config;
        config.num_nodes = 7;
        config.density = 0.6;
        config.back_arc_density = 0.3;   // cycles, so ng is load-bearing
        config.mixed_sign_costs = true;  // or a shortest path never revisits a node and ng
                                         // cannot bind -- see back_arc_density's doc comment
        config.with_time_window = true;  // the horizon is what keeps a cyclic instance finite
        config.with_ng_path = true;
        config.seed = seed;
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const double oracle = test_util::ng_cyclic_optimum(config);

        // The forward search agrees at this size too, so it is checked rather than assumed --
        // that is what makes DISABLED_CyclicOptimalityAtLargerSizes a statement about *size*.
        const auto forward = eq::solve_forward_ng(config);
        EXPECT_NEAR(forward.best_cost(), oracle, eq::kTolerance) << where;
        EXPECT_EQ(eq::any_path_problem(forward), "") << where;

        for (bool with_bound : {false, true}) {
            const auto bidi = eq::solve_bidirectional_ng(config, with_bound);
            EXPECT_NEAR(bidi.best_cost(), oracle, eq::kTolerance)
                << "bound=" << with_bound << " " << where;
            EXPECT_EQ(eq::any_path_problem(bidi), "")
                << "a joined path violated ng-feasibility: " << where;
        }
    }
}

// A pre-existing defect, found by this plan and recorded rather than fixed: on a **cyclic**
// instance past a certain size, the forward search and the half-way-**bounded** bidirectional
// search both return a suboptimal cost, while the **unbounded** bidirectional search matches the
// oracle exactly.
//
// Measured against a complete `ng_cyclic_optimum` (num_nodes = 8, density = 0.5,
// back_arc_density = 0.35, mixed_sign_costs, ng on):
//
//   seed   oracle       forward      bidi unbounded   bidi bounded
//      0    -2.424084    -2.424084     -2.424084       -2.424084
//      1    -3.406447    -2.839186     -3.406447       -2.839186   <-- forward & bounded miss
//      2    -9.716948    -9.716948     -9.716948       -9.716948
//      3   -20.475812   -18.018406    -20.475812      -18.018406   <-- forward & bounded miss
//      4    -5.427869    -5.427869     -5.427869       -5.427869
//      5   -20.934885   -20.934885    -20.934885      -20.934885
//
// The same shape appears at num_nodes = 9 on three of six seeds, with larger gaps (-34.65 vs
// -15.60 on seed 4). Both wrong answers replay as *feasible* paths, so this is lost solutions,
// not bad ones. That the forward search and the bounded bidirectional search agree to the last
// bit on every miss is the clue worth chasing first.
//
// Why this is DISABLED_ rather than deleted or asserted-as-correct: it states what *should*
// hold, so it is the regression test for a fix, and it must not be weakened to make it pass.
// It is out of scope for the shape-genericity plan -- nothing in steps 1-7 touches search or
// dominance -- and the generator has always been a DAG, so no shipped test covered this regime.
// The acyclic sweep is unaffected and still asserts full equality.
TEST(Equivalence, DISABLED_CyclicOptimalityAtLargerSizes) {
    namespace eq = equivalence_test;

    for (unsigned seed = 0; seed < 6; ++seed) {
        test_util::InstanceConfig config;
        config.num_nodes = 8;
        config.density = 0.5;
        config.back_arc_density = 0.35;
        config.mixed_sign_costs = true;
        config.with_time_window = true;
        config.with_ng_path = true;
        config.seed = seed;
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const double oracle = test_util::ng_cyclic_optimum(config);

        const auto forward = eq::solve_forward_ng(config);
        EXPECT_NEAR(forward.best_cost(), oracle, eq::kTolerance)
            << "the forward search lost solutions on a cyclic instance: " << where;

        for (bool with_bound : {false, true}) {
            const auto bidi = eq::solve_bidirectional_ng(config, with_bound);
            EXPECT_NEAR(bidi.best_cost(), oracle, eq::kTolerance)
                << "bound=" << with_bound << " " << where;
        }
    }
}

// The claim tier 2 rests on: ng must actually REJECT something on at least one of these seeds, or
// the test above is a second copy of tier 1 and nobody would notice.
//
// Without this, a later generator change that quietly widened the neighborhoods -- or lowered
// back_arc_density, or turned mixed_sign_costs off -- would hollow tier 2 out silently. It
// already earned its keep once: the first draft of the cyclic tier used non-negative costs, and
// this test is what showed that ng could not bind there at all, because a shortest path over
// non-negative arcs never revisits a node. Measured today: ng cuts the optimum on 5 of the 8
// seeds.
TEST(Equivalence, NgPathActuallyBindsOnAtLeastOneCyclicInstance) {
    namespace eq = equivalence_test;

    // One helper so the two configs cannot drift apart: everything is identical except the flag.
    const auto make_config = [](unsigned seed, bool with_ng) {
        test_util::InstanceConfig config;
        config.num_nodes = 9;
        config.density = 0.5;
        config.back_arc_density = 0.35;
        config.mixed_sign_costs = true;
        config.with_time_window = true;
        config.with_ng_path = with_ng;
        config.seed = seed;
        return config;
    };

    // Both sides go through the same search, so the forward search's cyclic defect cancels: the
    // question here is only whether ng changes the answer, not what the answer is.
    bool bound_somewhere = false;
    for (unsigned seed = 0; seed < 8; ++seed) {
        // Both solved through solve_forward_ng, i.e. the SAME two-slot graph type.
        // `with_ng_path = false` leaves the ng component present but inert -- empty forbidden
        // sets -- rather than absent, so the two runs differ in ng and not in label width.
        const auto restricted = eq::solve_forward_ng(make_config(seed, true));
        const auto unrestricted = eq::solve_forward_ng(make_config(seed, false));

        // A restriction can only make the optimum worse or leave it alone. If it is ever BETTER,
        // the ng component is not behaving as a restriction and something is wrong.
        if (!restricted.result.solutions.empty() && !unrestricted.result.solutions.empty()) {
            EXPECT_GE(restricted.best_cost(), unrestricted.best_cost() - eq::kTolerance)
                << "ng made the optimum BETTER, which a restriction cannot do, at seed " << seed;
        }

        const bool ng_cut_the_optimum =
            unrestricted.result.solutions.empty() != restricted.result.solutions.empty() ||
            (!restricted.result.solutions.empty() &&
             restricted.best_cost() > unrestricted.best_cost() + eq::kTolerance);
        if (ng_cut_the_optimum) {
            bound_somewhere = true;
        }
    }

    EXPECT_TRUE(bound_somewhere)
        << "ng never bound across 8 cyclic seeds: the neighborhoods are too loose, so the cyclic "
           "tier is testing nothing the acyclic tier does not already cover. Tighten the "
           "neighborhood window in test_util::ng_neighborhoods, or raise back_arc_density.";
}

// The generator's guard. The illegal combination must be refused at the draw, not documented --
// the tests are where someone will get this wrong.
//
// Only ONE combination is illegal. Cyclic + mixed-sign is legal and is what tier 2 uses: the
// window horizon bounds path length, so a negative cycle still has a finite optimum.
TEST(Equivalence, TheGeneratorRefusesTheIllegalCyclicCombinations) {
    test_util::InstanceConfig unbounded;
    unbounded.back_arc_density = 0.3;
    unbounded.with_time_window = false;
    EXPECT_THROW(test_util::draw_instance(unbounded), std::logic_error);

    // Cyclic + mixed-sign is explicitly allowed, and is what makes tier 2 non-vacuous.
    test_util::InstanceConfig pricing_shaped;
    pricing_shaped.back_arc_density = 0.3;
    pricing_shaped.mixed_sign_costs = true;
    pricing_shaped.with_time_window = true;
    EXPECT_NO_THROW(test_util::draw_instance(pricing_shaped));

    // And brute force stays acyclic: it walks forwards in node order with no visited set.
    test_util::InstanceConfig cyclic;
    cyclic.back_arc_density = 0.3;
    cyclic.with_time_window = true;
    EXPECT_THROW(test_util::brute_force_optimum(cyclic), std::logic_error);
}
