// Copyright (c) 2025 Laboratory for Combinatorial Optimization in Real-time Environment.
// All rights reserved.

#pragma once

// Phase 13: does the bidirectional algorithm produce the same answers as the forward one?
//
// The order here is deliberate and is the phase's whole point: correctness first, speed afterwards.
// **A policy that loses solutions looks fast.** Benchmark first and a large speedup tells you
// nothing about whether the work or the answers were pruned.
//
// What is compared, and what is not:
//
//   - **Best cost, within tolerance, never with `==`.** A forward run accumulates one chain of
//     additions; a joined path sums two independently accumulated chains, so the association order
//     differs and the totals disagree in the last bits.
//   - **Every returned path is replayed** through the model arc by arc and must be feasible at
//   every
//     node, contiguous, and run from a source to a sink. This is the check that catches a bad merge
//     producing a path neither algorithm would have generated by extension -- both would agree on
//     its cost while one returns nonsense.
//   - **Brute force**, on the small end: an enumerator that shares no code with either algorithm,
//   so
//     a dominance error common to both still shows up.
//
// What is NOT compared is the full solution *set*, which the phase plan asks for. The two
// algorithms do not have that property and cannot: a path whose forward prefix survives dominance
// at every node can still have a backward half that is dominated at the crossing node, so the join
// never emits it. Optimality is unaffected -- the dominating half yields a path at least as good --
// but the sets differ, and asserting equality would be a test that fails for a reason that is not a
// defect. `SolutionSetsAgreeOnTheOptimumNotOnEveryPath` pins the weaker property that does hold.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <limits>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>

#include "rcspp/rcspp.hpp"
#include "util/random_instance.hpp"

using namespace rcspp;  // NOLINT(google-build-using-namespace)

namespace equivalence_test {

using Composed = ResourceTypeComposition<RealResource>;
using Graph = ResourceGraph<RealResource>;

constexpr double kTolerance = 1e-9;

/// @brief A solve and the graph it ran on, kept together so the paths can be replayed afterwards.
struct Run {
        std::unique_ptr<Graph> graph;
        SolveResult result;
        bool bounded = false;

        [[nodiscard]] double best_cost() const {
            return result.solutions.empty() ? std::numeric_limits<double>::infinity()
                                            : result.solutions.front().cost;
        }
};

/// @brief The reference: an ordinary forward search.
inline Run solve_forward(const test_util::InstanceConfig& config) {
    Run run;
    auto built = test_util::build_instance(config);
    run.graph = std::move(built.graph);
    run.result = run.graph->solve<SimpleDominanceAlgorithm>(AlgorithmBaseParams{});
    return run;
}

/// @brief The candidate.
///
/// @param config       The instance to build.
/// @param with_bound   When false the half-way point is left at 0, which leaves the policy with no
///                     explicit `H` and no finite `R` to derive one from, so it starts disabled.
///                     That is the correct-but-slow path, and running every instance both ways is
///                     what isolates a disagreement to the bound rather than to the join.
inline Run solve_bidirectional(const test_util::InstanceConfig& config, bool with_bound) {
    Run run;
    auto built = test_util::build_instance(config);
    run.graph = std::move(built.graph);

    AlgorithmParams<LabelList<Composed>> params;
    params.critical_resource_index = built.clock_index;
    params.half_way_point = with_bound ? built.clock_upper_bound / 2.0 : 0.0;

    auto algorithm =
        run.graph->create_algorithm<BidirectionalAlgoBound<RealResource>::Algo>(params);
    run.result = run.graph->solve(algorithm.get());
    run.bounded = algorithm->bounded_by_half_way();
    EXPECT_TRUE(algorithm->get_label_pool().check_ref_count_consistency())
        << "reference counts must survive two searches and a join";
    return run;
}

/// @brief Replays one path through the model, returning what is wrong with it, or "".
///
/// Extends a fresh source resource arc by arc exactly as the search would, and requires every
/// intermediate node to be feasible. Mirrors what `FeasibilityPreprocessor` does with an arc's
/// extender, which is the only route to an arc's stored consumption.
inline std::string path_problem(const Graph& graph, const Solution& solution) {
    if (solution.path_arc_ids.empty()) {
        return "empty path";
    }

    const auto* first = graph.get_arc(solution.path_arc_ids.front());
    if (first == nullptr) {
        return "unknown arc id";
    }
    if (!first->origin->source) {
        return "path does not start at a source";
    }

    auto current = std::make_unique<Resource<Composed>>(*first->origin->resource);
    const Arc<Composed>* previous = nullptr;

    for (size_t arc_id : solution.path_arc_ids) {
        const auto* arc = graph.get_arc(arc_id);
        if (arc == nullptr) {
            return "unknown arc id";
        }
        if (previous != nullptr && previous->destination != arc->origin) {
            return "path is not contiguous at arc " + std::to_string(arc_id);
        }
        if (arc->extender == nullptr) {
            return "arc has no extender";
        }

        auto extended = std::make_unique<Resource<Composed>>(*arc->destination->resource);
        arc->extender->extend(*current, extended.get());
        if (!extended->is_feasible()) {
            return "path is infeasible at node " + std::to_string(arc->destination->id);
        }
        current = std::move(extended);
        previous = arc;
    }

    if (!previous->destination->sink) {
        return "path does not end at a sink";
    }
    return "";
}

/// @brief Replays every returned path and reports the first problem found.
inline std::string any_path_problem(const Run& run) {
    for (const auto& solution : run.result.solutions) {
        const std::string problem = path_problem(*run.graph, solution);
        if (!problem.empty()) {
            return problem;
        }
    }
    return "";
}

/// @brief The configurations the sweep runs, one per interesting combination of knobs.
///
/// Chosen rather than sampled: each row turns on one dimension the phase plan names, so a failure
/// points at a dimension instead of at "randomness". Seeds vary per row so the rows are not
/// correlated draws of the same graph.
inline std::vector<test_util::InstanceConfig> sweep() {
    std::vector<test_util::InstanceConfig> configs;

    // Cost only, sparse and dense. The clock is the cost slot, so the bound must switch itself off.
    configs.push_back({.num_nodes = 10, .density = 0.2, .seed = 1});
    configs.push_back({.num_nodes = 12, .density = 0.9, .seed = 2});

    // Time windows, loose and tight. Tight windows are where bidirectional wins and where a wrong
    // deadline shows.
    configs.push_back({.num_nodes = 14,
                       .density = 0.4,
                       .with_time_window = true,
                       .window_slack = 2.0,
                       .seed = 3});
    configs.push_back({.num_nodes = 14,
                       .density = 0.4,
                       .with_time_window = true,
                       .window_slack = 0.05,
                       .seed = 4});
    configs.push_back({.num_nodes = 24,
                       .density = 0.6,
                       .with_time_window = true,
                       .window_slack = 0.2,
                       .seed = 5});

    // Capacity, binding and not -- the Threshold clamp on its own.
    configs.push_back({.num_nodes = 12,
                       .density = 0.5,
                       .with_capacity = true,
                       .capacity_binds = true,
                       .seed = 6});
    configs.push_back({.num_nodes = 12,
                       .density = 0.5,
                       .with_capacity = true,
                       .capacity_binds = false,
                       .seed = 7});

    // Both, so the composition fans out over three components.
    configs.push_back({.num_nodes = 16,
                       .density = 0.5,
                       .with_time_window = true,
                       .window_slack = 0.5,
                       .with_capacity = true,
                       .capacity_binds = true,
                       .seed = 8});

    // Mixed-sign costs: the completion bound and the monotonicity fallback.
    configs.push_back({.num_nodes = 14, .density = 0.5, .mixed_sign_costs = true, .seed = 9});
    configs.push_back({.num_nodes = 18,
                       .density = 0.4,
                       .with_time_window = true,
                       .window_slack = 0.5,
                       .mixed_sign_costs = true,
                       .seed = 10});

    // Two sinks with different windows: per-node backward seeding.
    configs.push_back({.num_nodes = 15,
                       .density = 0.5,
                       .with_time_window = true,
                       .window_slack = 0.5,
                       .num_sinks = 2,
                       .seed = 11});
    configs.push_back({.num_nodes = 15,
                       .density = 0.5,
                       .with_capacity = true,
                       .capacity_binds = true,
                       .mixed_sign_costs = true,
                       .num_sinks = 2,
                       .seed = 12});

    // The large end, to catch anything that only appears with many labels per node.
    configs.push_back({.num_nodes = 40,
                       .density = 0.3,
                       .with_time_window = true,
                       .window_slack = 0.3,
                       .with_capacity = true,
                       .capacity_binds = true,
                       .seed = 13});

    return configs;
}

}  // namespace equivalence_test

// ============================================================================
// The equivalence sweep
// ============================================================================

/// @brief Bidirectional matches the forward search on every generated instance, bound on and off.
TEST(Equivalence, MatchesTheForwardSearchAcrossTheSweep) {
    namespace eq = equivalence_test;

    for (const auto& config : eq::sweep()) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const eq::Run reference = eq::solve_forward(config);
        const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
        const eq::Run unbounded = eq::solve_bidirectional(config, /*with_bound=*/false);

        EXPECT_EQ(reference.result.solutions.empty(), bounded.result.solutions.empty())
            << "one found solutions and the other did not: " << where;
        EXPECT_EQ(reference.result.solutions.empty(), unbounded.result.solutions.empty()) << where;

        if (!reference.result.solutions.empty()) {
            EXPECT_NEAR(bounded.best_cost(), reference.best_cost(), eq::kTolerance)
                << "bound enabled: " << where;
            EXPECT_NEAR(unbounded.best_cost(), reference.best_cost(), eq::kTolerance)
                << "bound disabled: " << where;
        }

        EXPECT_EQ(eq::any_path_problem(bounded), "") << "bound enabled: " << where;
        EXPECT_EQ(eq::any_path_problem(unbounded), "") << "bound disabled: " << where;
    }
}

/// @brief The bound never changes the answer, only how much work is done to reach it.
///
/// Asserted separately from the comparison against the forward search so that a disagreement is
/// attributable: if both bidirectional runs match each other but not the reference, the join is
/// wrong; if they disagree with each other, the half-way policy is.
TEST(Equivalence, TheHalfWayBoundDoesNotChangeTheAnswer) {
    namespace eq = equivalence_test;

    size_t instances_with_the_bound_in_force = 0;
    for (const auto& config : eq::sweep()) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
        const eq::Run unbounded = eq::solve_bidirectional(config, /*with_bound=*/false);

        EXPECT_NEAR(bounded.best_cost(), unbounded.best_cost(), eq::kTolerance) << where;
        EXPECT_FALSE(unbounded.bounded) << "half_way_point = 0 must leave the bound off: " << where;
        if (bounded.bounded) {
            ++instances_with_the_bound_in_force;
        }
    }

    // Otherwise the whole sweep would be measuring the disabled path twice and the "bound enabled"
    // half of every assertion above would be vacuous.
    EXPECT_GT(instances_with_the_bound_in_force, 0U)
        << "no instance in the sweep actually ran with the bound enabled";
}

/// @brief On cost-only instances there is no clock, so the bound refuses to engage.
///
/// Cost is the one resource that can never be the critical one -- reduced costs go negative -- and
/// the sweep deliberately contains instances with nothing else to point at.
TEST(Equivalence, ACostOnlyInstanceRunsWithTheBoundOff) {
    namespace eq = equivalence_test;
    const test_util::InstanceConfig config{.num_nodes = 10, .density = 0.4, .seed = 101};

    const eq::Run bounded = eq::solve_bidirectional(config, /*with_bound=*/true);
    EXPECT_FALSE(bounded.bounded) << "an accumulating cost slot is not a clock";
    EXPECT_NEAR(bounded.best_cost(), eq::solve_forward(config).best_cost(), eq::kTolerance);
}

// ============================================================================
// The independent oracle
// ============================================================================

/// @brief Both algorithms match an enumerator that shares no code with either.
///
/// Restricted to the small, sparse end: enumeration is exponential. It is worth having anyway --
/// comparing two label-setting algorithms cannot catch a dominance rule that is wrong in the same
/// way in both.
TEST(Equivalence, BothMatchBruteForceOnSmallInstances) {
    namespace eq = equivalence_test;

    const std::vector<test_util::InstanceConfig> configs{
        {.num_nodes = 8, .density = 0.4, .seed = 21},
        {.num_nodes = 9, .density = 0.3, .with_time_window = true, .window_slack = 0.3, .seed = 22},
        {.num_nodes = 9, .density = 0.3, .with_capacity = true, .capacity_binds = true, .seed = 23},
        {.num_nodes = 10, .density = 0.25, .mixed_sign_costs = true, .seed = 24},
        {.num_nodes = 10,
         .density = 0.25,
         .with_time_window = true,
         .window_slack = 0.4,
         .with_capacity = true,
         .capacity_binds = true,
         .num_sinks = 2,
         .seed = 25},
    };

    for (const auto& config : configs) {
        const std::string where = test_util::describe(config);
        SCOPED_TRACE(where);

        const double expected = test_util::brute_force_optimum(config);
        EXPECT_NEAR(eq::solve_forward(config).best_cost(), expected, eq::kTolerance)
            << "the forward search disagrees with enumeration: " << where;
        EXPECT_NEAR(eq::solve_bidirectional(config, /*with_bound=*/true).best_cost(),
                    expected,
                    eq::kTolerance)
            << "bidirectional disagrees with enumeration: " << where;
    }
}

/// @brief The solution sets agree on the optimum, and bidirectional never invents a path.
///
/// The phase plan asks for full set equality. That property does not hold and cannot: a path may
/// have a forward prefix that survives dominance everywhere and a backward half that is dominated
/// at the crossing node, in which case the join never emits it. What does hold is that every path
/// bidirectional returns is a genuine path of the graph, and that the optimum is among them.
TEST(Equivalence, SolutionSetsAgreeOnTheOptimumNotOnEveryPath) {
    namespace eq = equivalence_test;
    const test_util::InstanceConfig config{.num_nodes = 12,
                                           .density = 0.5,
                                           .with_time_window = true,
                                           .window_slack = 0.4,
                                           .seed = 31};
    const std::string where = test_util::describe(config);

    const eq::Run reference = eq::solve_forward(config);
    const eq::Run candidate = eq::solve_bidirectional(config, /*with_bound=*/true);
    ASSERT_FALSE(reference.result.solutions.empty()) << where;
    ASSERT_FALSE(candidate.result.solutions.empty()) << where;

    EXPECT_NEAR(candidate.best_cost(), reference.best_cost(), eq::kTolerance) << where;
    EXPECT_EQ(eq::any_path_problem(candidate), "") << where;

    // Every optimal path bidirectional returns must be one the forward search would accept as a
    // path, which replaying already establishes; the set sizes are allowed to differ.
    const size_t optimal_paths =
        static_cast<size_t>(std::ranges::count_if(candidate.result.solutions, [&](const auto& s) {
            return std::abs(s.cost - candidate.best_cost()) < eq::kTolerance;
        }));
    EXPECT_GT(optimal_paths, 0U) << where;
}
