// Copyright (c) 2025 Laboratory for Combinatorial Optimization in Real-time Environment.
// All rights reserved.

#pragma once

#include <cstddef>
#include <vector>

namespace rcspp {

/// @brief A single constraint-row entry used to build LP master-problem columns.
///
/// Each @c Row records the index of an LP constraint row and the coefficient
/// that a path (column) contributes to that row.
struct Row {
        /// @brief Zero-based index of the LP constraint row.
        size_t index;

        /// @brief Coefficient contributed by this arc to the LP constraint row.
        long double coefficient;
};

/// @brief Represents a column in the LP master problem generated by a path.
///
/// The @c cost field holds the sum of original arc costs along the path with no
/// dual contribution. The @c rows field accumulates constraint coefficients keyed
/// by row index (Row::coefficient values are summed per Row::index across all arcs
/// of the path).
struct Column {
        /// @brief Sum of original arc costs along the path (no dual contribution).
        double cost = 0.0;

        /// @brief Aggregated LP constraint coefficients for this column.
        ///
        /// Each entry represents a unique constraint row and the total coefficient
        /// that this path contributes to it.
        std::vector<Row> rows;
};

}  // namespace rcspp
