from __future__ import annotations

from typing import Any

# ── Generic base (not directly instantiated by users) ────────────────────────

class _ExtensionFunction: ...
class _FeasibilityFunction: ...
class _CostFunction: ...
class _DominanceFunction: ...

# ── Numerical resource functions (suffix: _real, _int, _uint) ────────────────

class AdditionExtensionFunction_real(_ExtensionFunction):
    def __init__(self) -> None: ...

class AdditionExtensionFunction_int(_ExtensionFunction):
    def __init__(self) -> None: ...

class AdditionExtensionFunction_uint(_ExtensionFunction):
    def __init__(self) -> None: ...

class ValueCostFunction_real(_CostFunction):
    def __init__(self) -> None: ...

class ValueCostFunction_int(_CostFunction):
    def __init__(self) -> None: ...

class ValueDominanceFunction_real(_DominanceFunction):
    def __init__(self) -> None: ...

class ValueDominanceFunction_int(_DominanceFunction):
    def __init__(self) -> None: ...

class TrivialFeasibilityFunction_real(_FeasibilityFunction):
    def __init__(self) -> None: ...

class TrivialFeasibilityFunction_int(_FeasibilityFunction):
    def __init__(self) -> None: ...

class TrivialCostFunction_real(_CostFunction):
    def __init__(self) -> None: ...

class TrivialCostFunction_int(_CostFunction):
    def __init__(self) -> None: ...

class MinMaxFeasibilityFunction_real(_FeasibilityFunction):
    def __init__(self, min_value: float, max_value: float) -> None: ...

class MinMaxFeasibilityFunction_int(_FeasibilityFunction):
    def __init__(self, min_value: int, max_value: int) -> None: ...

class TimeWindowExtensionFunction_real(_ExtensionFunction):
    def __init__(
        self, tw_by_node: dict[int, tuple[float, float]], default_max_value: float = ...
    ) -> None: ...

class TimeWindowFeasibilityFunction_real(_FeasibilityFunction):
    def __init__(
        self, tw_by_node: dict[int, tuple[float, float]], default_max_value: float = ...
    ) -> None: ...

# Signed numerical resources only: a budget counts down when extended backwards.

class BudgetExtensionFunction_real(_ExtensionFunction):
    def __init__(self, max_by_node: dict[int, float] = ..., default_max: float = ...) -> None: ...

class BudgetExtensionFunction_int(_ExtensionFunction):
    def __init__(self, max_by_node: dict[int, int] = ..., default_max: int = ...) -> None: ...

# ── Container resource functions (suffix: _bitset, _set) ─────────────────────

class UnionExtensionFunction_bitset(_ExtensionFunction):
    def __init__(self) -> None: ...

class UnionExtensionFunction_set(_ExtensionFunction):
    def __init__(self) -> None: ...

class IntersectionExtensionFunction_bitset(_ExtensionFunction):
    def __init__(self) -> None: ...

class InclusionDominanceFunction_bitset(_DominanceFunction):
    def __init__(self) -> None: ...

class ContainDominanceFunction_bitset(_DominanceFunction):
    def __init__(self) -> None: ...

class TrivialFeasibilityFunction_bitset(_FeasibilityFunction):
    def __init__(self) -> None: ...

class SizeFeasibilityFunction_bitset(_FeasibilityFunction):
    def __init__(self, min_size: int, max_size: int) -> None: ...

class TrivialCostFunction_bitset(_CostFunction):
    def __init__(self) -> None: ...
