name: Auto Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed for pushing changes

      # ----------------------
      # Python auto-format
      # ----------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python formatters
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run black and isort
        run: |
          black .
          isort .

      # ----------------------
      # C++ auto-format
      # ----------------------
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          files=$(find . -regex '.*\.\(cpp\|hpp\|cc\|hh\|cxx\|hxx\)')
          if [ -n "$files" ]; then
            clang-format -i $files
          fi

      # ----------------------
      # Commit and push changes if any
      # ----------------------
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto-format code (black, isort, clang-format)"
            git push origin HEAD:${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          fi
